import type { ExamQuestion } from "../types";

const DOMAIN = "agentic-architecture";

function q(
  id: string,
  question: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string
): ExamQuestion {
  return { id: `${DOMAIN}-${id}`, domain: DOMAIN, question, options, correctIndex, explanation };
}

export const AGENTIC_ARCHITECTURE_EXAM_1: ExamQuestion[] = [
  q("e1-1", "A team always runs the same four checks, in the same order, against every incoming document. Which best describes this system?", ["An agent, because it calls Claude", "A pipeline, because the sequence doesn't depend on intermediate results", "An agent, because it has multiple steps", "Neither — it's a single call"], 1, "A fixed sequence that doesn't change based on what any step returns is a pipeline, regardless of how many steps it has or whether a model is involved."),
  q("e1-2", "What is the primary architectural reason to prefer a pipeline over an agent when the task allows it?", ["Pipelines are always more accurate", "Pipelines are cheaper, faster, and easier to debug when the sequence is genuinely fixed", "Agents cannot call tools", "Pipelines don't require a system prompt"], 1, "When the sequence doesn't need to adapt to intermediate results, a pipeline achieves the same outcome with less cost, latency, and debugging surface."),
  q("e1-3", "An agentic loop calls a tool, and the tool result is malformed. What is the correct way to surface this back to the model?", ["Throw an exception and halt the loop", "Silently retry with the same arguments indefinitely", "Return a tool_result with is_error: true and a description of the failure", "Drop the tool_use block from history and continue"], 2, "Returning a structured tool_result with is_error: true lets the model see the failure and decide how to recover, rather than crashing the loop or hiding the failure."),
  q("e1-4", "Why is an iteration cap considered a required part of agentic loop design, not an optional safeguard?", ["It reduces token costs by ending loops early", "Without one, a loop that keeps finding reasons to call tools has no natural stopping point and can run indefinitely", "It is required by the tool_use API schema", "It improves the model's reasoning quality"], 1, "An unbounded loop is a production hazard specifically because nothing else guarantees termination — the cap is what bounds worst-case cost and runtime."),
  q("e1-5", "After an agent hits its iteration cap while stop_reason is still tool_use, what is the recommended way to end the loop cleanly?", ["Return an empty response to the user", "Make one more call with tool_choice: { type: \"none\" } to force a text answer", "Re-run the entire loop from scratch", "Silently truncate the last tool result"], 1, "Forcing tool_choice to none on a final call makes the model respond in text instead of requesting another tool, ending the loop with an actual answer rather than a mid-thought cutoff."),
  q("e1-6", "In an orchestrator/worker pattern, what does the orchestrator typically see from each worker?", ["The worker's full internal reasoning and every intermediate tool call", "Only the worker's final output", "Nothing — workers report directly to the end user", "The worker's system prompt"], 1, "Orchestrator/worker keeps the orchestrator's own context small by design — it integrates finished outputs, not the process that produced them."),
  q("e1-7", "A debate/verification multi-agent pattern is best justified when:", ["Every task, to maximize quality", "The output is high-stakes and prone to a specific error class (e.g. overconfident unverified claims) that a second pass can catch", "Latency is the top priority", "The task is simple classification"], 1, "Debate/verification pays a real latency and cost cost for a second pass — it earns that cost specifically on outputs where a known failure class is expensive to miss."),
  q("e1-8", "What is the main tradeoff introduced by splitting a task across multiple agents instead of one well-designed agent?", ["Multi-agent systems are always less accurate", "Coordination complexity, added latency from multiple round trips, and cost that multiplies rather than adds", "Multi-agent systems cannot use tools", "There is no meaningful tradeoff"], 1, "Multiple agents trade per-agent simplicity for a real coordination tax: more code, stacked latency, and multiplied (not additive) cost."),
  q("e1-9", "A pipeline stage that decides, based on the specific content of the current item, which follow-up question to ask next — a decision that can't be fully scripted in advance — is best described as:", ["Still a pipeline, since it's one stage of a larger fixed sequence", "An agentic sub-component embedded within an otherwise fixed pipeline", "A bug in the pipeline design", "A pure function"], 1, "A system can legitimately mix pipeline and agentic parts — the classification is about which specific decision genuinely depends on unscriptable intermediate information."),
  q("e1-10", "Why should raw transaction-level or record-level data typically stay client-side, with only aggregates sent to a server-side model call?", ["Aggregates are always more accurate", "It minimizes what sensitive data crosses a trust boundary, limiting exposure even if the server-side call is logged or misused", "The Messages API cannot accept large payloads", "It reduces the number of required tools"], 1, "This is a data-minimization / trust-boundary design decision: send only what's sufficient for the task, so a compromised or logged server-side call never had access to the raw sensitive data in the first place."),
  q("e1-11", "An agent with write access to a production system should, relative to a read-only research agent, generally have:", ["The same permissions — permissions shouldn't vary by task", "Broader tool access, since it needs to accomplish more", "Narrower tool scoping and more deliberate oversight, proportional to the cost of a mistake", "No system prompt at all"], 2, "Deployment architecture should reflect the cost of error: higher-stakes write access warrants narrower scope and more oversight, not the same treatment as low-stakes read access."),
  q("e1-12", "What should a well-designed agentic system do when its primary multi-step path fails entirely (e.g. a required tool is down)?", ["Return no response and let the client time out", "Have a defined degraded-but-functional fallback, or at minimum an honest failure message — not a silent, undefined failure", "Retry the exact same failing call indefinitely", "Automatically escalate to a different, unrelated task"], 1, "Production architecture should define what happens on failure explicitly — a visible honest failure or a degraded fallback both beat an undefined crash or a silent bad result."),
  q("e1-13", "Why are full agent transcripts considered the primary tool for debugging a wrong multi-step answer, rather than just inspecting the final output?", ["Transcripts are required by the API", "The mistake could be in any of several steps, and only the full sequence of tool calls and results shows which one actually went wrong", "Final outputs are never informative", "Transcripts reduce token costs"], 1, "A wrong final answer from a multi-step loop doesn't reveal which step caused it — only the full transcript lets you localize the actual point of failure."),
  q("e1-14", "A repeated pattern across many agent transcripts shows the same tool being called incorrectly in a specific situation. What does this most likely indicate?", ["The model is fundamentally unreliable and agents should be abandoned", "An underspecified tool description or ambiguous instruction, which is a fixable design issue", "A one-off, unexplainable fluke", "The iteration cap is set too high"], 1, "A recurring, specific misstep pattern is a signal about tool/prompt design quality, not random unreliability — and it points at a concrete, fixable cause."),
  q("e1-15", "Which of the following is the strongest signal that a task genuinely requires agentic architecture rather than a fixed pipeline?", ["The task involves calling an external API", "The task takes more than one step to complete", "The correct next action depends on information only available from a previous step's result, in a way that can't be predicted in advance", "The task is expensive to get wrong"], 2, "The defining test for 'agentic' is unscriptable dependency on intermediate results — not step count, tool use, or stakes alone (though stakes affect how much oversight the agent needs)."),
  q("e1-16", "Before building an agent, which of the following is NOT one of the four standard viability questions to check?", ["Complexity — is the task genuinely multi-step and hard to fully specify in advance?", "Value — does the outcome justify the added cost and latency?", "Popularity — is agentic architecture currently a popular technique?", "Cost of error — can a wrong intermediate decision be caught and recovered from?"], 2, "Popularity of a technique is irrelevant to whether it's the right architectural choice for a specific task — the real criteria are complexity, value, model viability, and cost of error."),
];

export const AGENTIC_ARCHITECTURE_EXAM_2: ExamQuestion[] = [
  q("e2-1", "A system always runs steps A, B, then C in that fixed order regardless of what A or B return, but step B happens to call Claude for summarization. This system is best classified as:", ["An agent, because a model is involved", "A pipeline with a model-calling stage, since the sequence itself is fixed", "Neither a pipeline nor an agent", "A multi-agent system"], 1, "Involving a model call doesn't make a stage agentic — the classification depends on whether the sequence of steps adapts to intermediate results, which it doesn't here."),
  q("e2-2", "Which scenario is the clearest candidate for genuinely agentic architecture?", ["Extracting a fixed set of fields from a well-structured form", "Deciding, based on what a document actually contains, which of several possible follow-up checks are needed", "Formatting a JSON response", "Translating a fixed sentence to another language"], 1, "A decision whose correct branch depends on the specific content discovered mid-task — not knowable in advance — is the core signature of agentic behavior."),
  q("e2-3", "In the standard tool-use loop, what does `messages.push({ role: \"assistant\", content: response.content })` immediately before appending the tool_result accomplish?", ["It deletes the previous tool call from history", "It preserves the model's tool_use block in history so the subsequent tool_result can be correctly associated with it", "It is unnecessary and can be skipped", "It resets the conversation"], 1, "The tool_result must reference a tool_use_id that exists in history — appending the assistant's tool_use turn is what makes that reference valid on the next call."),
  q("e2-4", "What is the risk of NOT capping the number of iterations in an agentic loop?", ["The model will refuse to respond", "A loop that keeps finding reasons to call tools can run indefinitely, with unbounded cost and no guaranteed termination", "The API will automatically stop after 3 calls regardless", "Nothing — loops always terminate naturally"], 1, "There's no built-in guarantee a loop terminates on its own; the cap is the only thing bounding worst-case runaway cost and runtime."),
  q("e2-5", "A pipeline pattern (draft → critique → revise) is generally easier to debug than an orchestrator/worker pattern primarily because:", ["It uses fewer tokens", "Each stage has one clear, fixed input/output contract, with no dynamic dispatch decision to trace", "It never fails", "It doesn't use any AI models"], 1, "A fixed sequence with clear per-stage contracts is simpler to reason about than a pattern where an orchestrator dynamically decides what to dispatch and to which worker."),
  q("e2-6", "Why does a debate/verification pattern specifically target overconfident or unverified claims as its failure class?", ["Because that's the only failure class LLMs have", "Because a second agent instructed specifically to find flaws is well-suited to catching claims a single confident pass wouldn't flag on its own", "Because it's cheaper than a single pass", "Because it eliminates the need for tools"], 1, "The pattern's value comes from assigning a second agent the explicit job of skepticism — which single-pass generation doesn't naturally provide."),
  q("e2-7", "What is the coordination tax of an orchestrator dispatching to three worker agents sequentially, each taking about 2 seconds?", ["No meaningful cost beyond a single call", "At least 6 seconds of stacked latency before accounting for any tool use inside each call", "Exactly the same latency as one call", "Latency decreases with more agents"], 1, "Sequential agent calls add up directly — three 2-second calls in sequence cost at least 6 seconds, on top of anything each call's own tool use adds."),
  q("e2-8", "If a worker agent's output is wrong because of a flaw in its internal process, but the orchestrator only sees the worker's final output, what does this imply for worker design?", ["Worker outputs should always be as short as possible", "Worker outputs should include brief reasoning, not just a bare answer, so failures are debuggable one level up", "The orchestrator should re-do all worker tasks itself", "This is not a real concern in practice"], 1, "Because context handoff between orchestrator and worker is lossy by design, making worker outputs self-explanatory is what keeps failures diagnosable without exposing full internal reasoning."),
  q("e2-9", "A financial app's agent computes an aggregate client-side and sends only `{ category: \"Dining\", total: 1240 }` to a server-side model call, never the underlying transactions. What architectural principle does this demonstrate?", ["Structured output constraints", "Data minimization across a trust boundary", "Prompt caching", "Multi-agent orchestration"], 1, "Sending only the minimum data sufficient for the task across a client/server trust boundary is a data-minimization and privacy-architecture decision, independent of any other technique."),
  q("e2-10", "Where should an agent's conversation state (the messages array) typically be considered to \"live\" between requests in a production system?", ["Nowhere — the API stores it automatically", "Explicitly in application-owned storage (a database, cache, or client state), since the API itself is stateless", "In the model's weights", "It doesn't need to be stored"], 1, "Because the Messages API is stateless, production architecture must explicitly decide where and how conversation history persists between requests — that's an application-level responsibility."),
  q("e2-11", "A credit-decisioning agent serving a large customer base and an internal documentation-drafting agent both use the same underlying agentic-loop pattern. Why might they be architected very differently?", ["They shouldn't be — identical patterns require identical architecture", "The cost of a wrong decision differs enormously, which should drive differences in oversight, permission scope, and autonomy", "Only one of them can technically use tools", "Documentation agents cannot use the agentic loop"], 1, "Stakes-appropriate architecture means the same underlying mechanism can and should be deployed with very different oversight and scoping depending on the real-world cost of an error."),
  q("e2-12", "What is the most direct benefit of logging a brief stated reason before each tool call (\"why I'm calling this tool\") in an agent's transcript?", ["It reduces the number of tool calls needed", "It turns an otherwise opaque tool-selection decision into something a human can review after the fact", "It is required by the tool schema", "It prevents all errors from occurring"], 1, "Visible reasoning doesn't prevent mistakes, but it makes them reviewable — turning 'the agent picked a weird tool' into a diagnosable, specific cause."),
  q("e2-13", "An agent's loop ends with stop_reason: \"tool_use\" still set after hitting the iteration cap, and no forced final-answer call is made. What is the likely user-facing result?", ["A complete, well-formed answer", "No text response, or an incomplete response, since the model never actually replied in text", "An error from the API itself", "The loop automatically restarts"], 1, "Without a forced final call, hitting the cap while still awaiting a tool call leaves nothing but an unresolved tool request — there's no guaranteed text answer to show the user."),
  q("e2-14", "Which of these is the best example of designing for graceful degradation in agent architecture?", ["Assuming the agent will always succeed and adding no fallback", "Defining a simpler, non-agentic fallback path that can still produce a usable (if lesser) result when the primary agentic path is unavailable", "Retrying the exact same failing request forever", "Removing all error handling to simplify the code"], 1, "Graceful degradation means the system keeps functioning, even in a reduced form, rather than having only one path that fails completely when unavailable."),
  q("e2-15", "Why is \"the task takes multiple steps\" alone NOT sufficient justification for agentic architecture?", ["Multi-step tasks are always better as pipelines", "A fixed multi-step sequence with no dependency on intermediate results is a pipeline, not an agent, regardless of step count", "Agents can only take one step", "Step count is irrelevant to any architectural decision"], 1, "Step count doesn't determine agentic-ness — what matters is whether the sequence of steps must adapt based on what earlier steps actually returned."),
  q("e2-16", "A system's observability data shows the same tool being mis-selected in the same recurring scenario. What is the appropriate response?", ["Increase the iteration cap", "Treat it as a signal to revise that tool's description or the relevant instruction, since the pattern points to a specific, fixable design gap", "Ignore it as expected model variance", "Switch to a completely different model with no other changes"], 1, "A specific, recurring misstep pattern is diagnostic information pointing at a fixable design issue — not random noise to be tolerated or worked around with an unrelated change."),
];

export const AGENTIC_ARCHITECTURE_EXAM_3: ExamQuestion[] = [
  q("e3-1", "A model-governance triage system applies the same fixed risk-scoring criteria to every submission, but then an agent decides which specific follow-up documentation to request based on what's missing. Which statement is accurate?", ["The whole system is a pipeline", "The whole system is an agent", "The triage portion is a pipeline; the follow-up-request portion is agentic — a single system can contain both", "Neither classification applies to governance systems"], 2, "Real systems often mix fixed, pipeline-like stages with genuinely agentic decision points — classification applies per-decision, not to the system as a monolith."),
  q("e3-2", "What distinguishes a genuinely agentic step from a pipeline step that merely happens to call an LLM?", ["Whether the LLM call is expensive", "Whether the next action is decided by the model based on intermediate results, rather than fixed in advance by the calling code", "Whether the step uses tools", "Whether the step is implemented in TypeScript or Python"], 1, "The presence of an LLM call doesn't make a step agentic — what matters is whether the model's own output, not the surrounding code, decides what happens next."),
  q("e3-3", "In a tool-use loop, if a model requests two tools in parallel within one turn, what is the correct way to return their results?", ["Return each tool_result in a separate follow-up message", "Return both tool_result blocks together in a single user message", "Only return the result for the first tool called", "Discard the parallel results and ask the model to call them one at a time"], 1, "Parallel tool_use blocks from one turn must be answered together in a single user message with all corresponding tool_result blocks — splitting them across messages breaks the expected pattern."),
  q("e3-4", "What is the primary purpose of forcing `tool_choice: { type: \"none\" }` after an agentic loop hits its iteration cap?", ["To make the next tool call cheaper", "To force the model to produce a text answer instead of requesting yet another tool, ending the loop cleanly", "To reset the conversation history", "To disable all future tool use permanently"], 1, "This forces a text response on that specific call so the loop can end with an actual answer, rather than being cut off mid tool-request."),
  q("e3-5", "Which best describes when an orchestrator/worker pattern is worth its added complexity?", ["Whenever more than one tool is involved", "When sub-tasks are genuinely independent or need meaningfully different models/instructions, and a single context would otherwise become unmanageable", "Only when cost is not a concern", "Never — a single agent is always preferable"], 1, "Orchestrator/worker earns its coordination cost specifically when sub-tasks are independent enough to benefit from separate, focused contexts or different model tiers."),
  q("e3-6", "A pipeline pattern is described as having \"no dynamic dispatch decision.\" What does this mean?", ["The pipeline cannot call any tools", "The order and choice of stages is fixed in advance; only the content flowing through each stage varies", "The pipeline runs on dynamically allocated cloud infrastructure", "The pipeline requires a database"], 1, "Unlike orchestrator/worker, a pipeline's structure (which stages run, in what order) doesn't change based on results — only the data passing through it does."),
  q("e3-7", "Why might a debate/verification pattern be a poor fit for a low-stakes, high-volume classification task?", ["Debate/verification cannot be applied to classification", "The added latency and doubled cost aren't justified when the cost of an occasional wrong classification is low", "It always produces worse accuracy", "It requires a database"], 1, "Debate/verification pays a real cost for its extra pass — that cost is only justified when the value of catching the specific error class it targets is high enough, which isn't the case for cheap, low-stakes volume work."),
  q("e3-8", "A team splits a task across 4 agents when a single well-designed agent with better tool descriptions could have handled it in one context. What is the most likely consequence?", ["Guaranteed higher accuracy", "Unnecessary coordination complexity, latency, and cost with no corresponding benefit", "Reduced token usage", "Elimination of all failure modes"], 1, "Multi-agent architecture is a real tradeoff, not a free upgrade — applying it where a single agent would suffice adds cost and complexity without a matching benefit."),
  q("e3-9", "What does it mean for a tool's return value to respect data-minimization principles in agent architecture?", ["The tool returns as much data as possible for flexibility", "The tool returns only the aggregated or derived data sufficient for the task, not raw underlying sensitive records", "The tool has no input schema", "The tool never returns an error"], 1, "Minimizing what crosses a trust boundary — sending only what's needed, not the full raw dataset — is a deliberate architectural choice that limits exposure if that data is later logged, intercepted, or misused."),
  q("e3-10", "An agent operating with only a read-only search tool receives a prompt-injected instruction attempting to delete data. What limits the actual damage?", ["The model's own judgment alone", "The scoped tool permissions — an agent with no delete-capable tool cannot delete data no matter what an injected instruction says", "The length of the conversation", "The model's training cutoff date"], 1, "Least-privilege tool scoping is what actually bounds the blast radius of a followed injected instruction — if the capability doesn't exist as a tool, the instruction can't be carried out regardless of intent."),
  q("e3-11", "Where should conversation state for a multi-turn agent be stored if the server hosting the agent restarts mid-conversation?", ["It's lost, and this is acceptable to leave undefined", "In durable, application-owned storage decided in advance, with an explicit, defined recovery behavior (resume, restart, or fail visibly)", "The API automatically persists and recovers it", "In the model weights"], 1, "Production architecture should define recovery behavior for mid-task failures explicitly, since the API provides no server-side persistence of its own."),
  q("e3-12", "A system has no fallback if its primary agentic path fails — the feature simply goes fully unavailable. What architectural gap does this represent?", ["Missing observability", "Missing graceful degradation", "Missing tool schemas", "Missing a system prompt"], 1, "A system with exactly one path and no fallback fails completely the moment that path fails — the fix is a defined degraded mode, which is what graceful degradation means."),
  q("e3-13", "Which detail is LEAST useful to include in an agent's execution log, relative to the others, for debugging purposes?", ["The exact arguments of every tool call", "Whether each tool_result was is_error: true or a success", "The total character count of the system prompt", "The model's stated reasoning before each tool call, if requested"], 2, "System prompt length has little diagnostic value for understanding a specific wrong decision — the other three directly help reconstruct what the agent actually did and why."),
  q("e3-14", "A recurring failure shows an agent calling the wrong tool specifically when two tools have overlapping, similarly-worded descriptions. What is the most targeted fix?", ["Increase max_tokens", "Sharpen and differentiate the two tools' descriptions so their boundaries are less ambiguous to the model", "Remove all tools and use a single call instead", "Ignore it — this is unfixable model behavior"], 1, "Tool selection reliability is driven heavily by how clearly descriptions communicate purpose and boundaries — ambiguous, overlapping descriptions are a fixable root cause, not an inherent limitation."),
  q("e3-15", "Which of the following would most strongly argue AGAINST building an agent for a given task?", ["The task is high-value if done correctly", "A wrong intermediate decision would be silent, hard to detect, and hard to reverse, with no review step available", "The task requires calling two tools", "The task takes about 5 seconds to complete with a single call"], 1, "High cost-of-error with no way to catch or reverse a mistake is one of the four core viability checks — when it fails, added model-driven autonomy is a liability, not a benefit."),
  q("e3-16", "A requirements-automation agent decides mid-run, based on discovery notes it just read, to check an open regulatory requirement before proceeding — a branch not scripted in the code. What does this demonstrate?", ["A bug in the pipeline", "Genuine agentic behavior: an unscripted decision driven by intermediate results", "A failure of the iteration cap", "A violation of least-privilege tool design"], 1, "This is the defining signature of agentic behavior from this module: a next step chosen by the model based on what it discovered, not predetermined by the code."),
];
