import type { ExamQuestion } from "../types";

const DOMAIN = "context-reliability";

function q(
  id: string,
  question: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string
): ExamQuestion {
  return { id: `${DOMAIN}-${id}`, domain: DOMAIN, question, options, correctIndex, explanation };
}

export const CONTEXT_RELIABILITY_EXAM_1: ExamQuestion[] = [
  q("e1-1", "Why must a full conversation history be resent on every request to the Messages API?", ["Because the API caches it automatically and only needs a diff", "Because the API is stateless — the model has no memory of a prior turn unless it's included again in the current request", "Because the model requires it for billing purposes only", "This is not actually required; history is optional"], 1, "The API holds no server-side memory between requests — anything the model needs to know from earlier in the conversation must be included again in the current request."),
  q("e1-2", "A response is cut off mid-sentence. What does checking `stop_reason` most likely reveal?", ["stop_reason: \"end_turn\"", "stop_reason: \"max_tokens\", indicating the response hit its length ceiling rather than concluding naturally", "stop_reason: \"refusal\"", "stop_reason is not populated on truncated responses"], 1, "A truncated, mid-thought response corresponds to stop_reason: \"max_tokens\" — a hard ceiling being hit, not the model choosing to end its turn."),
  q("e1-3", "Why is conversation length a real cost factor even when the newest question is short?", ["Short questions are always charged a flat fee", "The entire prior history is resent and billed as input tokens on every single turn, regardless of how short the newest addition is", "Cost is determined only by output length", "Long conversations are billed at a discount"], 1, "Because the full history is resent each turn, growing conversation length directly increases the input-token cost of every subsequent turn, independent of the newest message's length."),
  q("e1-4", "What is the recommended default mitigation for unbounded conversation-history growth in a production chat feature?", ["Let history grow without limit — larger context windows make this a non-issue", "Cap history at a fixed number of recent turns (e.g. the last 20) as a safety valve", "Delete the system prompt after the first turn", "Switch models every 5 turns"], 1, "Truncating to a bounded window of recent turns is a standard, simple safety valve against unbounded token growth and context dilution."),
  q("e1-5", "A tool returns every underlying transaction record instead of a computed total. What is the main downside in a long-running agent?", ["The tool becomes impossible to call", "That full payload gets resent and re-billed on every subsequent turn, compounding the cost as the conversation continues", "The tool result becomes immutable", "There is no meaningful downside"], 1, "Bulky tool results don't just cost once — they remain in history and get re-sent (and re-billed) on every later turn unless actively pruned or summarized."),
  q("e1-6", "What is the difference between compaction and context editing, as two distinct context-management mechanisms?", ["They are the same mechanism with different names", "Compaction summarizes earlier context; context editing clears specific content (like old tool results) rather than summarizing it", "Context editing is only available for images", "Compaction deletes the system prompt"], 1, "These are genuinely distinct mechanisms — one produces a summary to replace older content, the other removes specific content outright without summarizing it."),
  q("e1-7", "Why is cross-session memory described as \"not automatic\" and a deliberate design decision?", ["Because it's technically impossible to build", "Because a new conversation has zero built-in knowledge of a previous one — persisting facts across sessions requires an explicitly built extraction-and-storage system", "Because the API forbids storing any user data", "Because memory would make responses too fast"], 1, "The API has no built-in concept of persisting facts across separate conversations — any cross-session memory has to be deliberately engineered (extract, store, re-inject), which is a design choice, not a limitation to work around silently."),
  q("e1-8", "Why is prompt caching most effective when stable content (system prompt, tool definitions) is placed before variable content (the user's specific message)?", ["Caching only works on the very first message of a conversation", "Caching matches on a shared prefix — placing volatile content after the cached prefix keeps that prefix identical across requests, preserving cache hits", "Variable content cannot be included in cached requests at all", "Order has no effect on caching behavior"], 1, "Since caching depends on an unchanged shared prefix, keeping the parts that vary per-request after the cacheable block is what preserves the cache hit on repeated calls."),
  q("e1-9", "What does a near-zero `cache_read_input_tokens` value across repeated, seemingly-identical requests most likely indicate?", ["Caching is working exactly as intended", "A silent invalidator — something in the supposedly-stable prefix is actually varying between requests (e.g. a timestamp or unsorted JSON)", "The account has exceeded its rate limit", "The requests are using different API keys"], 1, "A near-zero cache-read rate on requests that should share a prefix is the standard symptom of an unnoticed variation breaking the prefix match — worth auditing for things like embedded timestamps or non-deterministic ordering."),
];

export const CONTEXT_RELIABILITY_EXAM_2: ExamQuestion[] = [
  q("e2-1", "A tool result that's no longer needed for any future decision in the conversation is still kept verbatim in history. What is the recommended fix?", ["Leave it — removing any history is always unsafe", "Replace it with a short summary, or drop it entirely once it's fully superseded, since it's still being resent and billed on every later turn", "Convert it to an image", "Increase max_tokens to compensate"], 1, "Once a tool result has served its purpose, summarizing or dropping it keeps the accumulating context lean without losing anything still needed going forward."),
  q("e2-2", "Why can a very large but underused context window still hurt response quality if filled unnecessarily?", ["Large context windows always improve quality regardless of content", "Past a point, relevant information can get diluted among irrelevant context, which can measurably reduce quality even though the window technically fits everything", "This scenario is purely hypothetical and never happens in practice", "Filling the context window reduces the number of available tools"], 1, "A large context window changes what's technically possible, not what's efficient — irrelevant filler can dilute the model's attention on what actually matters, independent of whether it technically fits."),
  q("e2-3", "What must be preserved when using server-side compaction across multiple turns?", ["Only the extracted plain-text summary needs to be kept", "The full compaction block from the response must be appended back into message history, not just its text — losing the block loses the compacted state", "Nothing needs to be preserved; compaction is fully automatic and stateless", "Only the original uncompacted messages, discarding the compaction block"], 1, "The compaction block itself carries state the API relies on for subsequent requests — extracting only the text and discarding the block silently loses that state."),
  q("e2-4", "An agent processes 50 similar items in one long run, keeping every prior item's full detail in context. What happens by item 50?", ["Nothing — context windows are effectively unlimited", "Most of the context budget is spent re-reading the previous 49 items rather than reasoning about the current one, unless earlier items are summarized down", "The API automatically discards old items for you", "The agent's tool permissions expire"], 1, "Without active summarization or pruning, a long run's accumulated context increasingly crowds out the budget available for the actual current task."),
  q("e2-5", "Why should 429 (rate limit) and 5xx (server) errors generally be retried, while 400-class errors generally should not?", ["400 errors are more severe and always need urgent escalation", "429/5xx are typically transient and often succeed on retry; a 400 reflects a malformed request that will fail identically every time without a code fix", "Retrying is never appropriate for any error code", "400 errors resolve automatically after a fixed delay"], 1, "429/5xx often reflect temporary conditions worth retrying; a 400 reflects a structurally invalid request that retrying won't fix — only correcting the request will."),
  q("e2-6", "What is the purpose of a \"repair loop\" for malformed structured output?", ["To immediately show the raw error to the end user", "To send the invalid output back to the model with a description of what failed, asking for a corrected version, resolving many failures without human intervention", "To permanently disable structured output after one failure", "To retry the exact same request with no changes"], 1, "Feeding the validation failure back to the model as context for a corrected attempt resolves a meaningful share of structured-output failures automatically, at the cost of one extra round trip."),
  q("e2-7", "Why does idempotency matter more for agentic retries than for typical human-driven retries?", ["Idempotency is only a concern for human users, not agents", "An agent mid-loop facing an ambiguous timeout may retry a side-effecting call automatically and immediately, more readily than a cautious human operator would", "Agents cannot make side-effecting tool calls at all", "Idempotency has no relevance to agent architecture"], 1, "An agent's automated retry behavior under uncertainty makes accidental duplicate side effects more likely than a human pausing to check first — which is exactly why idempotency protection matters more here."),
  q("e2-8", "A system has no defined behavior when its primary path is unavailable, and simply goes fully dark. What reliability principle is missing?", ["Prompt caching", "Graceful degradation — a defined, even if reduced, fallback path or an honest failure message", "Strict tool schemas", "Chain-of-thought prompting"], 1, "The absence of any degraded mode means one failure takes the whole feature down — the fix is a defined fallback or, at minimum, a visible, honest failure state."),
  q("e2-9", "Why is a silently-defaulted failure considered worse than a visible, propagated error?", ["Visible errors always crash the entire application", "A silent default that looks like a valid result removes the ability to even detect that something went wrong, let alone debug or fix it", "Silent failures are actually preferable in production systems", "There is no meaningful difference between the two"], 1, "A visible error, however inconvenient, can be seen, logged, and investigated — a silently swallowed one that masquerades as success can propagate undetected indefinitely."),
];

export const CONTEXT_RELIABILITY_EXAM_3: ExamQuestion[] = [
  q("e3-1", "What does `usage.input_tokens` include on a multi-turn conversation's later requests?", ["Only the newest user message", "The system prompt, every prior message resent, and any accumulated tool-result content included in the request", "Only tokens generated by the model in its response", "Nothing — input tokens are not tracked per-request"], 1, "Because the full history is resent each turn, input_tokens on a later turn reflects everything included in that request — system prompt, prior turns, and accumulated results — not just what's new."),
  q("e3-2", "Why is `max_tokens` described as a \"hard ceiling,\" not a target?", ["Because responses are always exactly max_tokens long", "Because hitting it truncates the response mid-generation rather than the model choosing to stop there naturally", "Because it only applies to streaming requests", "Because it has no effect on output length"], 1, "max_tokens caps how much can be generated; being cut off at that cap produces a truncated, unfinished response rather than a deliberately concluded one — an important distinction to check via stop_reason."),
  q("e3-3", "A conversation history summarization strategy keeps the most recent N turns verbatim and compresses older turns into a summary. What is the rationale for this asymmetry?", ["Older information is always irrelevant and can be discarded entirely", "Recent context usually matters most for precision, while older context can often tolerate being compressed to a gist without losing what's still needed", "Verbatim storage is required by the API for all turns", "This asymmetry has no real justification"], 1, "Recency-weighted context management reflects that the most immediately relevant detail is usually recent, while a gist of older context is often sufficient for what's still needed going forward."),
  q("e3-4", "Why is cross-session memory built as an explicit extract-store-reinject system rather than left to accumulate automatically?", ["Automatic accumulation is technically impossible", "Unbounded automatic accumulation would make agent behavior progressively harder to predict and audit — deliberate, scoped memory keeps it legible", "Explicit memory systems are always more expensive to build", "There is no difference in outcome between the two approaches"], 1, "A deliberately scoped memory system (what gets extracted, stored, and re-injected) keeps behavior auditable — unbounded silent accumulation would make it much harder to reason about what the agent 'knows' at any point."),
  q("e3-5", "Which error-handling pattern correctly distinguishes retryable from non-retryable failures?", ["Catch one broad exception type and retry every failure identically", "A most-specific-first chain that retries 429/5xx/connection errors but not 400-class validation errors", "Never retry anything, under any circumstances", "Retry only 400-class errors, never 429/5xx"], 1, "Catching a single broad error class loses the important distinction between transient failures worth retrying and structural failures that need a code fix instead — a specific-first chain preserves that distinction."),
  q("e3-6", "What should happen when a structured-output repair loop's corrected attempt also fails validation?", ["Keep retrying indefinitely with no limit", "Surface a visible, structured failure rather than silently returning a default or looping forever", "Silently return the original malformed output anyway", "Disable structured output permanently for all future requests"], 1, "A repair loop should have a bound — after a reasonable number of attempts, an unresolved failure should surface visibly rather than looping forever or being quietly discarded."),
  q("e3-7", "A tool wrapping a \"send notification\" action is called twice due to an agent retry. What design choice prevents two notifications from being sent?", ["Increasing the tool's timeout value", "Idempotency — either making the action naturally idempotent or requiring an idempotency key that lets the second call be recognized as a repeat", "Removing the tool's description", "Adding more required fields to the schema"], 1, "This is a direct application of idempotency protection to a real side-effecting tool — without it, an uncertain-success retry risks a duplicate real-world action."),
  q("e3-8", "Why is `cache_read_input_tokens` a more reliable signal of caching health than simply assuming caching \"works\" because `cache_control` was set?", ["Setting cache_control guarantees a cache hit with no exceptions", "A silent invalidator (e.g. a timestamp embedded in the prefix) can break caching even when cache_control is correctly set, so the actual usage field is the ground truth to check", "cache_read_input_tokens is unrelated to whether caching succeeded", "Caching cannot be verified after the fact"], 1, "Setting cache_control expresses intent, but whether a cache hit actually occurred is a fact you should verify from the response's usage data, since subtle prefix instability can silently defeat caching."),
  q("e3-9", "A long agent run accumulates growing tool-result context across many steps with no summarization. Besides increasing cost, what is the other named risk?", ["Improved accuracy from more available context", "Reduced accuracy, because relevant information can become diluted among an increasing volume of stale, no-longer-relevant context", "The agent becomes unable to call any further tools", "The conversation automatically resets"], 1, "Beyond the direct cost of resending growing context, unmanaged growth can measurably hurt quality by burying what's still relevant under accumulated, largely irrelevant history."),
];
