import type { ExamQuestion } from "../types";

const DOMAIN = "prompt-engineering";

function q(
  id: string,
  question: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string
): ExamQuestion {
  return { id: `${DOMAIN}-${id}`, domain: DOMAIN, question, options, correctIndex, explanation };
}

export const PROMPT_ENGINEERING_EXAM_1: ExamQuestion[] = [
  q("e1-1", "A prompt says \"review this code\" with no further detail. What is the most likely problem?", ["The model will refuse to respond", "The task is ambiguous between several plausible interpretations (bugs vs. style vs. explanation), and the model will guess rather than know which one is wanted", "The prompt is too long", "This is a perfectly sufficient prompt"], 1, "Without stating the specific task explicitly, a model has to guess among several reasonable interpretations — the fix is stating the actual goal directly."),
  q("e1-2", "What is generally more reliable for getting a model to follow a specific format: describing the format in the abstract, or providing one worked example of it?", ["Describing it in the abstract is always better", "Providing one or two well-chosen examples (few-shot) often outperforms abstract description, especially for edge cases the description didn't anticipate", "Neither has any effect on output", "Examples only work for code generation tasks"], 1, "A concrete example removes ambiguity about edge cases that a purely descriptive instruction may not have covered."),
  q("e1-3", "Why is \"don't be verbose\" considered a weaker instruction than \"respond in 2-3 sentences\"?", ["Negative instructions are always ignored entirely", "The negative instruction leaves the target open to interpretation, while the positive instruction gives a concrete, checkable target", "Positive instructions require fewer tokens", "There is no meaningful difference"], 1, "A positive, concrete instruction is easier to satisfy exactly than an open-ended negative one, which only states what to avoid without defining the actual target."),
  q("e1-4", "What belongs in the system prompt versus the first user message, according to standard practice?", ["Everything belongs in the system prompt", "The system prompt should describe persistent behavior (tone, constraints, role); the user turn should carry the specific task at hand", "Everything belongs in the user message; system prompts are deprecated", "The user message should contain only single words"], 1, "Splitting persistent behavioral instructions from the specific per-request task is the standard separation, and it also enables prompt caching on the stable portion."),
  q("e1-5", "Why does keeping user-supplied content out of the system prompt improve injection resistance?", ["It doesn't — placement has no security effect", "It keeps the boundary between \"instruction\" and \"data\" explicit, rather than blurring untrusted content into the persistent instruction channel", "System prompts are encrypted while user messages are not", "User messages are never processed by the model"], 1, "Structural separation of instructions from data is a core injection-resistance pattern — mixing untrusted content into the system prompt erodes that boundary."),
  q("e1-6", "A persona is defined only with positive, easy-case instructions and has never been tested against pushback or adversarial phrasing. What is the risk?", ["No risk — personas are static and can't degrade", "The persona may not hold up once a user provides an edge case or adversarial input the definition didn't anticipate", "The persona will use more tokens than necessary", "This is the correct and complete way to define a persona"], 1, "A persona is only as robust as the cases it's been tested against — untested edge cases and adversarial pushback are exactly where an underspecified persona tends to break down."),
  q("e1-7", "What does role prompting (\"respond as a senior security engineer\") actually change about a model's output?", ["It grants the model new information it didn't otherwise have", "It shapes tone, vocabulary, and framing, without adding underlying capability or knowledge the model lacked", "It disables the model's safety behavior", "It has no measurable effect"], 1, "Role prompting is a framing tool that shapes communication style — it doesn't grant new facts or reasoning ability the model wouldn't otherwise have access to."),
  q("e1-8", "When should chain-of-thought / step-by-step reasoning be requested?", ["For every single request, regardless of task", "For tasks that genuinely require chaining several intermediate deductions — not for simple single-inference tasks like basic classification", "Only for tasks under 10 words", "Never — it always reduces quality"], 1, "Reasoning-eliciting prompts pay off specifically on genuinely multi-step problems; requesting it for a single-inference task adds cost and latency without improving accuracy."),
  q("e1-9", "Why is \"just ask the model to respond in JSON\" considered insufficiently reliable for production use?", ["JSON is not supported by the API at all", "Free-text compliance can drift — an extra sentence of preamble, a stray code fence, or a missing field can slip through and break a parser", "Because it costs significantly more money", "Because it disables tool use permanently"], 1, "Plain-text formatting instructions rely on the model's free-text compliance, which is usually good but not guaranteed — production systems need a stronger, schema-enforced guarantee."),
  q("e1-10", "What is the recommended mechanism for reliably guaranteeing a specific JSON output shape?", ["Repeating \"respond only in JSON\" multiple times in the prompt", "A tool-based structured output approach (a tool whose input_schema is the desired shape) or native structured outputs, both of which are schema-validated", "Asking the model politely and trusting it", "Using all capital letters in the instruction"], 1, "Schema-backed mechanisms (tool-based extraction or native structured outputs) push the format guarantee into the request's contract with the API, rather than relying on free-text compliance."),
  q("e1-11", "A schema-validated extraction returns a well-formed object where the `dueDate` field is a plausible-looking but incorrect date. What does this demonstrate?", ["The schema mechanism failed", "Structural validity (shape) and semantic correctness (accuracy) are different guarantees — schema validation only ensures the former", "This is impossible with structured output", "The date field should be removed from the schema"], 1, "Schema-constrained output guarantees the shape is correct; it says nothing about whether the specific values inside that shape are actually true, so semantic validation is still needed separately."),
  q("e1-12", "Why is testing a prompt change only against the single example that motivated the change considered a mistake?", ["It takes too much time", "It provides no evidence about whether the change broke something else that was previously working — a representative test set is needed for that", "The API charges extra for repeated testing", "Prompt changes cannot be tested at all"], 1, "A single-example check can confirm the targeted case improved, but says nothing about unintended regressions elsewhere — a broader test set is what actually reveals that."),
];

export const PROMPT_ENGINEERING_EXAM_2: ExamQuestion[] = [
  q("e2-1", "What is the most reliable way to ensure a model produces exactly three bullet points?", ["Hope the model infers this from context", "State the exact requirement explicitly (\"respond with exactly three bullet points\")", "Use a longer, more elaborate prompt overall", "Ask the model to guess how many points are appropriate"], 1, "Explicit, stated constraints on format and quantity are far more reliable than relying on the model to infer an unstated preference."),
  q("e2-2", "Which is generally the higher-leverage lever for improving output quality: rephrasing an instruction more cleverly, or providing the specific context/background the task actually depends on?", ["Clever rephrasing, every time", "Providing the actual relevant context and constraints usually moves quality more reliably than searching for cleverer phrasing of the same instruction", "Neither has any effect", "Only prompt length matters"], 1, "Concrete, relevant context (facts, constraints, examples of 'good') tends to outperform iterating on phrasing of an otherwise underspecified instruction."),
  q("e2-3", "A system prompt states a persona's knowledge boundary explicitly: \"You have access only to the retrieved policy documents provided.\" What purpose does this serve?", ["It has no functional effect, it's just flavor text", "It constrains the model to answer from the provided context rather than filling gaps from general training knowledge", "It disables tool use", "It is required syntax for the Messages API"], 1, "Explicitly stating knowledge boundaries in the system prompt is what makes a grounding/no-hallucination instruction concrete and enforceable, rather than vague."),
  q("e2-4", "Why should a standing grounding rule (\"answer only from provided sources\") go in the system prompt rather than being repeated in every user turn?", ["Repeating it every turn is required by the API", "It's a persistent behavioral rule, so stating it once in the system prompt is both more reliable and more cache-friendly than restating it per turn", "User turns cannot contain instructions", "System prompts are not billed for tokens"], 1, "A rule that applies to the whole conversation belongs in the system prompt — this is both the correct semantic placement and preserves prompt-caching benefits across turns."),
  q("e2-5", "A model is asked to \"think step by step\" before answering a simple, single-lookup factual question. What is the likely effect?", ["Significantly improved accuracy", "Added output tokens and latency with little to no accuracy benefit, since there's no real multi-step chain to work through", "The model will refuse the request", "The answer will be shorter"], 1, "Chain-of-thought prompting pays off on genuinely multi-step reasoning; applying it to a task that doesn't need chaining just adds cost without a matching benefit."),
  q("e2-6", "What does an `effort` setting on extended thinking primarily control?", ["The model's vocabulary choices", "The depth of internal reasoning and associated token spend, replacing the need to manually engineer a chain-of-thought instruction", "The temperature/randomness of output", "Whether tool use is enabled"], 1, "Extended thinking with an effort level is the modern mechanism for controlling reasoning depth, largely superseding hand-written 'think step by step' prompt engineering for supported models."),
  q("e2-7", "Why should visible model reasoning be spot-checked against the final answer when it's being used to justify or audit a decision?", ["Because reasoning is always identical to the final answer", "Because stated reasoning can occasionally be inconsistent with the actual final answer, so faithfulness shouldn't be assumed without checking", "Because reasoning text is never actually generated", "Because this check is unnecessary in all cases"], 1, "Visible reasoning isn't guaranteed to be perfectly faithful to how the final answer was actually reached — when reasoning is load-bearing (used to justify a decision), that gap is worth checking for."),
  q("e2-8", "What is the risk of a structured-output schema having no way to represent \"no extractable data found\"?", ["No risk — every input will always contain extractable data", "The model may be forced to hallucinate plausible-looking values to satisfy the schema, rather than accurately indicating absence", "The schema will fail to validate at all", "This has no effect on output quality"], 1, "A schema with no negative-case representation forces the model into producing something that technically satisfies the shape even when the honest answer is 'not present' — designing for that case explicitly avoids this."),
  q("e2-9", "Why is comparing two candidate prompts on the same fixed test set, scored the same way, preferred over trying one, then the other, sequentially and judging by feel?", ["Sequential comparison is always faster", "A fixed test set removes the variability of the tester's own attention or mood shifting between attempts, giving a more reliable comparison", "Sequential comparison is required by best practice", "There's no meaningful difference between the two approaches"], 1, "A/B comparison against a fixed, consistently scored test set is more reliable than an inherently subjective sequential 'which felt better' judgment."),
  q("e2-10", "What is a realistic risk of over-iterating a prompt against a very small test set?", ["The prompt will use less context", "The prompt can overfit to quirks specific to that small set, in a way that doesn't generalize to new inputs", "The API will reject overly-tuned prompts", "There is no such risk — more iteration is always better"], 1, "Just like model overfitting, a prompt tuned obsessively against a narrow set of examples can pick up quirks that don't hold up on the broader range of real input."),
  q("e2-11", "Which pairing correctly matches a scenario to the more appropriate mechanism?", ["Need a guaranteed exact JSON shape → plain-text \"please respond in JSON\" instruction", "Need a guaranteed exact JSON shape → a strict, schema-validated tool or native structured output", "Need a persuasive tone shift → a JSON schema", "Need multi-step reasoning on a trivial lookup → chain-of-thought prompting"], 1, "Schema-backed mechanisms are the right tool specifically when a guaranteed shape is required — the other pairings mismatch mechanism to need."),
  q("e2-12", "A prompt iteration log records what changed, what test set it ran against, and the result, for every attempted revision. What problem does this most directly prevent?", ["Increased token costs", "Repeating the same already-tried, already-failed experiment because nobody remembered it was tried before", "Model refusals", "Schema validation failures"], 1, "Without a record, prompt iteration tends to re-litigate the same ideas repeatedly — a log turns iteration into an accumulating, checkable body of evidence."),
];

export const PROMPT_ENGINEERING_EXAM_3: ExamQuestion[] = [
  q("e3-1", "A prompt gives an instruction but omits the intended audience for the explanation. What is the likely consequence?", ["The model will always default to an expert-level explanation", "The model has to guess the audience, and may produce an explanation pitched at the wrong level for the actual reader", "This detail never affects output", "The model will ask a clarifying question every time"], 1, "Audience is exactly the kind of unstated requirement a model can't reliably infer — leaving it out produces a guess, not a targeted answer."),
  q("e3-2", "What is the main advantage of a single well-chosen few-shot example over several paragraphs of abstract formatting instructions?", ["Examples always use fewer tokens", "An example demonstrates edge-case handling directly, which abstract instructions often fail to fully anticipate or specify", "Abstract instructions are against best practice and should never be used", "Examples eliminate the need for a system prompt"], 1, "A concrete example resolves ambiguity about specific edge cases in a way that generalized descriptive instructions often can't fully anticipate."),
  q("e3-3", "Why does mixing the actual task instructions into the system prompt alongside persona and safety rules make caching less effective?", ["It doesn't — caching is unaffected by this", "If the task content changes on every request, it invalidates the otherwise-stable cached prefix, since caching requires an unchanged shared prefix", "System prompts cannot be cached under any circumstances", "Caching only applies to user messages, never system prompts"], 1, "Caching benefits from a stable, unchanging prefix — folding per-request variable content into the system prompt breaks that stability and forfeits the caching benefit."),
  q("e3-4", "A persona states what it prioritizes when instructions conflict (e.g., \"prefer completeness over brevity when they conflict\"). Why does this matter?", ["It has no effect on real behavior", "It tells the model how to resolve tradeoffs it will actually face mid-response, rather than leaving that resolution undefined", "It is required syntax", "It only matters for creative writing tasks"], 1, "Real responses often hit genuine tradeoffs; a persona that specifies priority under conflict gives the model a concrete resolution rule instead of leaving it to guess."),
  q("e3-5", "What is the primary difference between extended thinking (`type: \"adaptive\"`) and older manually-engineered \"think step by step\" prompting?", ["They are functionally identical in every way", "Extended thinking uses a built-in mechanism with a controllable effort level, largely replacing the need to hand-craft the reasoning instruction in prompt text", "Manual chain-of-thought prompting is always more accurate", "Extended thinking disables tool use"], 1, "Built-in extended thinking with an effort parameter is the more direct, model-native mechanism for controlling reasoning depth on supported models, superseding most manual chain-of-thought prompt engineering."),
  q("e3-6", "Why is asking for step-by-step reasoning on a narrow classification task considered wasteful rather than merely neutral?", ["It causes the request to fail", "It adds real output tokens (cost and latency) for a task that doesn't have a meaningful chain to reason through, with no accuracy benefit to offset that cost", "It has no measurable cost at all", "It is required for all classification tasks"], 1, "Reasoning tokens are a real, billed cost — spending them on a task that gains nothing from chaining is a straightforward waste, not a harmless extra."),
  q("e3-7", "A tool-based structured-output schema uses a free-text `category` string instead of an enum, even though the valid categories are a small fixed set. What is the downside?", ["No downside — free text is always preferable", "The model can return an out-of-set or malformed category value that an enum would have prevented outright", "Enums are not supported in JSON Schema", "Free text fields cannot be validated at all"], 1, "Wherever the input space is enumerable, using an enum in the schema is what actually prevents invalid values, rather than merely making them easier to catch after the fact."),
  q("e3-8", "Why does structured output narrow, but not eliminate, the need for a retry/repair path in production?", ["Structured output always eliminates every possible failure", "Even schema-validated mechanisms can occasionally fail to produce a valid response under unusual or adversarial input, so a repair path still has value", "Structured output has no relationship to reliability at all", "Retry paths are never actually needed with any mechanism"], 1, "Schema guarantees dramatically reduce format failures but don't make them impossible — production systems still benefit from a fallback repair mechanism for the residual cases."),
  q("e3-9", "What is the purpose of testing a prompt specifically against adversarial or unusually-phrased inputs, not just clean examples?", ["Adversarial inputs are rare enough to ignore", "Real users rarely phrase requests exactly the way the prompt's author did, and the actual behavior boundary of a prompt often lives in these harder cases", "It only matters for security-focused applications", "Clean examples are always sufficient for validating a prompt"], 1, "A prompt's real-world robustness is best revealed by the harder, more varied inputs it will actually encounter — testing only clean cases leaves the true behavior boundary unexamined."),
  q("e3-10", "If a prompt change shows no measurable improvement on a reasonably sized, representative test set, what is the appropriate next step?", ["Keep making unmeasured tweaks indefinitely until it feels better", "Consider whether the test set itself is too narrow, or conclude the bottleneck may lie elsewhere (tool design, retrieved context, task difficulty) rather than the prompt itself", "Immediately conclude the model is incapable of the task", "Increase max_tokens as the default fix"], 1, "Diminishing returns on a representative test set is a signal to either broaden the test set or look past the prompt itself for the actual bottleneck, rather than continuing to iterate blindly."),
  q("e3-11", "A schema-validated extraction tool is given `strict: true`. Which failure mode does this NOT prevent?", ["A missing required field", "An unexpected extra field", "A field with the wrong data type", "A field containing a plausible but factually incorrect value"], 3, "Strict mode enforces structural correctness (types, required fields, no extras) but has no way to verify that a structurally valid value is also factually accurate."),
  q("e3-12", "What does it mean to treat a prompt as a \"versioned artifact\"?", ["Prompts should never be changed once written", "Changes are made deliberately, tested against a representative set before being trusted, and can be rolled back if they regress — the same discipline applied to code", "Only the most recent version of a prompt should ever be kept", "Prompts should be rewritten from scratch for every new request"], 1, "This is the core discipline of prompt iteration: deliberate, tested, reversible changes — not a one-time draft, and not untracked ad hoc edits either."),
];
