import type { ExamQuestion } from "../types";

const DOMAIN = "tool-design-mcp";

function q(
  id: string,
  question: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string
): ExamQuestion {
  return { id: `${DOMAIN}-${id}`, domain: DOMAIN, question, options, correctIndex, explanation };
}

export const TOOL_DESIGN_MCP_EXAM_1: ExamQuestion[] = [
  q("e1-1", "What does Claude actually produce when it \"uses\" a tool?", ["Claude directly executes code on your server", "A structured request naming the tool and its arguments — your code decides whether and how to run it", "A finished result, bypassing your code entirely", "A new tool definition"], 1, "Claude never executes anything itself — it only requests a tool call, and your code retains full control over whether and how that request is actually carried out."),
  q("e1-2", "Why does a tool's `description` field matter as much as its schema?", ["It has no real effect on behavior", "Claude decides whether and when to call a tool based largely on how well the description communicates its purpose and limits", "It is only shown to end users", "It determines the tool's execution speed"], 1, "A vague description produces unreliable tool selection; a specific one that states purpose and limits produces reliable selection — this is a functional, not cosmetic, property."),
  q("e1-3", "A tool named `run_query` accepts a single free-text SQL string. What is the main risk of this design?", ["It is too slow", "It gives the model latitude to construct arbitrary — potentially wrong or dangerous — queries, and the space of possible calls isn't reviewable in advance", "It cannot be cached", "It requires no input schema"], 1, "A broad, flexible tool trades away the reviewability and safety that come from a narrow, bounded set of possible calls."),
  q("e1-4", "What does marking a tool as `strict: true` (with `additionalProperties: false` and a complete `required` list) guarantee?", ["The tool will never fail", "The returned tool_use input validates exactly against the schema — no missing or unexpected fields", "The tool runs faster", "The tool cannot be called in parallel with others"], 1, "Strict mode moves the validation guarantee earlier, into the contract itself, rather than requiring defensive checks after the fact in your tool function."),
  q("e1-5", "Why should a tool's authentication credentials for an external system never be visible to the model?", ["Because the model cannot process strings", "Because it removes an entire category of prompt-injection risk — there's no credential in context for an injected instruction to try to exfiltrate", "Because it violates the tool's input schema format", "Credentials should actually be included for transparency"], 1, "Keeping credentials entirely server-side, never in the model's context, closes off a specific injection-based exfiltration risk in addition to being a general security best practice."),
  q("e1-6", "What is the correct response when a side-effecting tool call fails due to a network timeout, and it's unclear whether the underlying action completed?", ["Assume it failed and retry immediately with the same arguments", "Rely on idempotency protection (an idempotency key or a naturally idempotent operation) so a retry doesn't duplicate the effect", "Never retry any side-effecting tool", "Tell the model to guess whether it succeeded"], 1, "Uncertain-success side effects need idempotency protection specifically because a blind retry could duplicate a real-world action if the original call actually did succeed."),
  q("e1-7", "What does MCP (Model Context Protocol) standardize?", ["How the model internally reasons about a task", "The interface between an AI application and external systems, so any MCP client can use any MCP server", "The pricing of Claude API requests", "The exact wording of system prompts"], 1, "MCP standardizes the protocol between applications and the systems they connect to — analogous to how HTTP standardizes browser-server communication — not anything about the model's internal reasoning."),
  q("e1-8", "From Claude's point of view, how does an MCP-provided tool differ from a hand-rolled tool defined directly in your code?", ["MCP tools are always faster", "They look identical — a name, description, and schema — because MCP doesn't change how the model itself thinks about tools", "MCP tools cannot have input schemas", "MCP tools bypass the tool-use loop entirely"], 1, "MCP changes how your application acquires and manages tools, not how the model perceives or selects them — to the model, both look like ordinary tool definitions."),
  q("e1-9", "When should you reach for an MCP server instead of writing a hand-rolled tool?", ["Always, for every tool", "When integrating with a system that already has a maintained MCP server, or when the same integration needs to be reusable across multiple applications", "Only for tools with no side effects", "Never — MCP is strictly worse than hand-rolled tools"], 1, "MCP earns its adoption specifically when reuse across applications or avoiding rebuilding an already-maintained integration is the actual goal — not as a universal default."),
  q("e1-10", "Why should tool descriptions supplied by a third-party MCP server be treated as untrusted input to the model?", ["Because MCP servers cannot be trusted to run at all", "Because a malicious or compromised server could craft a tool description to manipulate the model's behavior, similar to prompt injection", "Because MCP tool descriptions are always in a different language", "Because MCP tools have no name field"], 1, "A connected MCP server effectively supplies content that reaches the model's context — the same injection caution that applies to any external content applies to a server's tool descriptions."),
  q("e1-11", "A tool that only needs read access to a policy database is instead given the same broad read/write service account used elsewhere in the system. What design principle does this violate?", ["Strict mode", "Least privilege — the tool's access should be scoped to exactly the job its description claims, not the full permissions of its underlying credential", "Prompt caching", "Parallel tool use"], 1, "Least-privilege tool scoping means each tool's actual access should match its stated job exactly — reusing an overly broad credential undermines the reviewability that narrow tool design is meant to provide."),
];

export const TOOL_DESIGN_MCP_EXAM_2: ExamQuestion[] = [
  q("e2-1", "Which best completes: \"Tool use lets Claude ___ that your code run something.\"", ["execute", "request", "guarantee", "prevent"], 1, "Claude only ever requests a tool call — execution and the decision of whether to actually run it remain entirely in your code's control."),
  q("e2-2", "A tool description says only \"gets data.\" What is the most likely consequence?", ["Perfect tool selection every time", "Unreliable tool selection, since the model has little signal about when this tool should or shouldn't be used", "The tool will fail to execute", "The schema becomes optional"], 1, "Vague descriptions provide little signal for the model's tool-selection decision, which directly produces unreliable calling behavior."),
  q("e2-3", "What is the main security benefit of decomposing one broad, flexible tool into several narrow, specific tools?", ["It reduces the number of API calls needed", "The space of possible calls per tool becomes small and reviewable in advance, rather than open-ended", "It automatically encrypts all tool arguments", "It removes the need for a description field"], 1, "Narrow tools bound what's actually possible per call, which is what makes their behavior reviewable and their risk assessable — a broad tool's possibility space is much harder to fully audit."),
  q("e2-4", "Enums and required fields in a tool's input_schema primarily serve to:", ["Make the schema longer for documentation purposes", "Eliminate entire classes of malformed calls before they can form, rather than catching them after the fact", "Slow down tool execution intentionally", "Replace the need for a tool description"], 1, "Constraining the valid input space directly in the schema prevents invalid calls from ever being generated, which is stronger than validating and rejecting them after the model has already committed to a bad call."),
  q("e2-5", "Why is schema versioning (e.g., `check_status_v2`) recommended for a breaking change to a live tool's shape?", ["Because tool names must be unique globally", "Because mutating a live tool's contract can silently break anything that cached the old schema or replayed an old conversation using it", "Because Claude cannot use tools with numbers in their names", "It is not actually necessary — tools can change shape freely"], 1, "Treating a breaking tool schema change like a breaking API change avoids silently breaking existing callers, cached assumptions, or replayed conversations built against the old shape."),
  q("e2-6", "What is the correct way to handle a rate-limited (429) response from an external API inside a tool function?", ["Let the exception propagate uncaught to crash the agent loop", "Return a structured tool_result with is_error: true and a clear message, so the model can react appropriately", "Silently return an empty success result", "Immediately switch to a different unrelated tool"], 1, "A rate limit is a real, recoverable failure that should reach the model as a structured, informative error — not as a crash or a disguised fake success."),
  q("e2-7", "MCP's client/server relationship is most analogous to which existing standardization pattern?", ["A single vendor's proprietary API format", "HTTP standardizing how browsers talk to servers, regardless of which browser or server implementation is used", "A compiled binary format", "A specific programming language's syntax"], 1, "MCP standardizes the interface layer the same way HTTP does — any compliant client can talk to any compliant server without custom, one-off integration work."),
  q("e2-8", "An organization has 5 internal AI tools, each separately re-implementing the same lookup against an internal policy system. What does MCP most directly solve here?", ["It makes each hand-rolled integration faster", "It replaces 5 duplicated bespoke integrations with one maintained server that every client can reuse", "It removes the need for any authentication", "It merges all 5 tools into a single monolithic tool"], 1, "This is the core economic case for MCP: converting N-apps-times-M-integrations duplication into N clients and M reusable servers."),
  q("e2-9", "Why is it recommended to keep a policy-lookup MCP server strictly read-only, separate from any tool capable of modifying that same data?", ["Read-only servers are always faster", "Bundling a read capability with a write capability in one tool blurs a permission boundary that should be explicit and separately reviewable", "MCP servers cannot support write operations at all", "It reduces the size of the tool description"], 1, "Keeping distinct authority levels (read vs. write) as separate, narrowly scoped tools keeps what an agent can actually do legible and reviewable from the tool list alone."),
  q("e2-10", "What does parallel tool use require of your response handling?", ["Only the first requested tool needs a result returned", "All tool_result blocks for every tool_use block in that turn must be returned together in a single follow-up message", "Each parallel tool call needs its own separate API request", "Parallel tool calls are not supported and should be avoided"], 1, "Claude waits for closure on every tool_use block it emitted in a turn — returning only some results, or splitting them across messages, is a common source of confusion in the loop."),
  q("e2-11", "A tool wrapping a payment-charging API is called twice due to a client-side retry after an ambiguous timeout. What prevents a duplicate charge?", ["Nothing — duplicate charges are an accepted risk", "An idempotency key that lets the second call be recognized as a repeat of the first, rather than a new charge", "Increasing the tool's max_tokens", "Renaming the tool"], 1, "Idempotency protection is specifically designed for this exact scenario — an uncertain-success retry on a side-effecting operation — preventing the retry from duplicating the real-world effect."),
];

export const TOOL_DESIGN_MCP_EXAM_3: ExamQuestion[] = [
  q("e3-1", "Which of the following is the clearest sign a tool's description needs improvement?", ["The tool has a required field", "The model frequently calls the tool at inappropriate times, or fails to call it when it should", "The tool returns JSON", "The tool has fewer than 5 parameters"], 1, "Selection errors — over-triggering or under-triggering — are the direct, observable symptom of a description that doesn't clearly communicate when the tool should and shouldn't be used."),
  q("e3-2", "What is the risk of a tool function that trusts its schema alone to guarantee sane input, with no additional validation?", ["None — schema validation is always sufficient", "The model can still emit a schema-valid but semantically wrong value (e.g. a made-up but well-formed city name), which the tool function should still check", "Schemas cannot be validated at request time", "This describes the only correct approach"], 1, "Schema validation guarantees shape, not correctness — a syntactically valid but hallucinated or nonsensical value can still pass schema checks, so tool functions should validate meaningfully, not just structurally."),
  q("e3-3", "A tool call fails and your code catches the exception, logs nothing, and returns a default empty value that looks like a normal successful result. What is wrong with this?", ["Nothing — this is correct error handling", "It silently disguises a real failure as a success, which is worse than a visible error because it can't be detected or debugged later", "It uses too much memory", "It violates the tool's input schema"], 1, "A silently swallowed failure that looks identical to success is one of the most dangerous failure patterns — it removes the ability to even detect that something went wrong."),
  q("e3-4", "Why does MCP's standardization benefit specifically apply to your application code and not to the model's behavior?", ["Because the model refuses to use MCP tools", "Because MCP governs how your application discovers and manages tool integrations; the model still just sees ordinary tool definitions either way", "Because MCP only works with one specific model", "Because MCP requires no schema at all"], 1, "This is the detail that trips people up about MCP: it's an application-and-integration-layer standard, not a change to how the model itself reasons about or selects tools."),
  q("e3-5", "What is the appropriate scope for an MCP server that only needs to look up a model's governance classification?", ["Full read/write access to the entire governance database, for flexibility", "Narrow, read-only access limited to the specific lookup it needs to perform", "No access at all, since it should only use cached data", "Access to every internal system, in case it's needed later"], 1, "Least-privilege scoping applies to MCP servers the same way it applies to hand-rolled tools — grant only what the stated job actually requires."),
  q("e3-6", "A tool schema marks `city` as `required` and constrains it to a fixed enum of supported cities. What class of error does this prevent?", ["Network timeouts", "The model returning an unsupported or hallucinated city name that would otherwise need to be caught after the call", "Slow API responses", "Model refusals"], 1, "Enumerating the valid input space directly in the schema prevents an entire category of invalid values from ever being generated in the first place."),
  q("e3-7", "Why is authentication described as belonging to \"your code, never the model\"?", ["Because models cannot store any information", "Because credentials should never enter the model's context at all — the tool function handles auth entirely on its own, invisibly to the model", "Because the model would reject any request containing credentials", "Because credentials must be included in the tool's description field"], 1, "The model only ever needs the tool's structured inputs/outputs to do its job — credentials belong entirely inside the tool function's implementation, never passed through or visible in the conversation."),
  q("e3-8", "A team wraps a public GitHub API both as a hand-rolled tool and as a connection to an existing maintained MCP server, then compares the two. What is this comparison mainly useful for evaluating?", ["Which one uses fewer tokens per response", "The tradeoff between control/customization (hand-rolled) and reduced integration effort/reusability (MCP)", "Which one is compatible with tool_choice", "Neither approach can be meaningfully compared"], 1, "This is exactly the practical tradeoff the module highlights: hand-rolled tools give more control over app-specific logic, while MCP trades some of that control for reuse and reduced integration work."),
  q("e3-9", "What does `strict: true` NOT guarantee about a tool call?", ["That the input matches the schema's types", "That every required field is present", "That the values are semantically correct, not just structurally valid", "That there are no unexpected extra fields"], 2, "Strict mode guarantees structural validity — types, required fields, no extras — but says nothing about whether the values themselves are factually or semantically correct."),
  q("e3-10", "An MCP client connects to a new, unfamiliar MCP server. What is the most accurate way to describe what this grants?", ["Nothing changes until the client actually calls a tool", "It's equivalent to granting a new agent authority to whatever real systems that server can reach — connecting is itself a meaningful trust decision", "It only grants read access by default in all cases", "MCP servers cannot expose consequential actions"], 1, "Because MCP servers can expose real, consequential capabilities, connecting a client to a new one should be treated as a genuine authority-granting decision, not a neutral configuration step."),
  q("e3-11", "Which pairing correctly matches a tool-design failure mode with its fix?", ["Broad do-anything tool → fix by adding more free-text parameters", "Ambiguous overlapping tool descriptions → fix by sharpening and differentiating the descriptions", "Silent swallowed errors → fix by removing all error handling", "Missing idempotency on a side-effecting tool → fix by retrying more aggressively"], 1, "Ambiguous, overlapping descriptions are directly fixed by making each tool's boundary clearer and more distinct — the other three options each describe a fix that would make the underlying problem worse, not better."),
];
